"""Deploy artifact templates.

Everything the operator ever reads on a fresh deploy: compose.yml +
envvars.example + README.md. Kept as Python strings (not Jinja files)
because the substitutions are trivial and shipping a second templating
layer for three files reads as ceremony.

The compose file emits ONE service on ``--network=host``. The image
tag is baked in at generation time so ``pixie-lab init`` on a v0.4.0
CLI pins the container at ``ghcr.io/safl/pixie:0.4.0``; the operator
can bump manually to track ``:latest`` if they want to.
"""

from __future__ import annotations

from typing import Any

DEFAULT_IMAGE_REPO = "ghcr.io/safl/pixie"
DEFAULT_ADMIN_PASSWORD = "pixie"

# NBD supervisor's default port range base -- kept in lockstep with
# ``pixie.exports._supervisor.DEFAULT_PORT_BASE``.
DEFAULT_NBD_PORT_BASE = 10809
DEFAULT_HTTP_PORT = 8080

COMPOSE_YAML = """\
# pixie compose deployment. One service, one HTTP port + NBD range,
# session-auth on write routes gated by ``PIXIE_ADMIN_PASSWORD``.
#
# Bring up with:
#     cp envvars.example envvars
#     "${{EDITOR:-vi}}" envvars     # set PIXIE_HOST_ADDR + PIXIE_ADMIN_PASSWORD
#     COMPOSE_ENV_FILES=envvars podman compose up -d
#
# ``--network=host`` is the whole point of pixie's one-container
# shape: udp/69 (once the in-process TFTP router lands), tcp/8080
# (HTTP), and the NBD port range all reach the LAN without any
# port-publish hoops. Operators fronting pixie behind a reverse proxy
# can drop network_mode: host and publish 8080 explicitly.
services:
  pixie:
    image: {image}
    container_name: pixie
    restart: unless-stopped
    network_mode: host
    environment:
      PIXIE_ADMIN_PASSWORD: ${{PIXIE_ADMIN_PASSWORD:-{admin_password}}}
      PIXIE_PUBLIC_HOST: ${{PIXIE_HOST_ADDR:-127.0.0.1}}
      PIXIE_NBD_PUBLIC_HOST: ${{PIXIE_HOST_ADDR:-127.0.0.1}}
      # Optional per-target kernel workarounds appended to the
      # pixie-live-env cmdline. Empty by default. Known-good values
      # for specific hardware live in the src/pixie/pxe/_routes.py
      # docstring; set here if any of your PXE targets need one.
      # Example (GIGABYTE MC12-LE0): pci=realloc=on,nocrs
      PIXIE_LIVE_ENV_EXTRA_CMDLINE: ${{PIXIE_LIVE_ENV_EXTRA_CMDLINE:-}}
    volumes:
      - ./data:/var/lib/pixie:Z
    # Container HEALTHCHECK is baked in the Containerfile; compose
    # picks it up automatically.
"""

ENVVARS_EXAMPLE = """\
# Fill this in and rename to ``envvars``. Both fields below are
# REQUIRED for a functional deploy.
#
# COMPOSE_ENV_FILES=envvars podman compose up -d
#
# PIXIE_HOST_ADDR is the LAN address pixie tells iPXE targets to
# use. Set it to the address ON YOUR LAN this box answers on; if
# left unset the plans point at 127.0.0.1 and a target that boots
# the plan can't reach pixie's HTTP / NBD.
PIXIE_HOST_ADDR=

# Session-auth password for the operator UI + write routes.
# Default is public knowledge; set your own.
PIXIE_ADMIN_PASSWORD={admin_password}

# Per-target kernel workarounds appended to the pixie-live-env
# cmdline. Empty by default; set on a target-by-target basis.
#
# Known-good values:
#   GIGABYTE MC12-LE0 (Ryzen server board):
#     PIXIE_LIVE_ENV_EXTRA_CMDLINE=pci=realloc=on,nocrs
#   That board's BIOS has a ROM BAR overlap defect that leaves no
#   MMIO space for the Intel i210 NICs; without the workaround the
#   live env boots with no working network, live-boot never fetches
#   the squashfs, and boot hangs silently.
PIXIE_LIVE_ENV_EXTRA_CMDLINE=
"""

README_MD = """\
# pixie deploy

Generated by ``pixie-lab init``.

## Layout

* ``compose.yml``     -- compose stack. One service on ``--network=host``.
* ``envvars.example`` -- environment overrides. Copy to ``envvars`` and edit.
* ``data/``           -- persistent state (blobs + artifacts + state.db).

## Bring up

```
cp envvars.example envvars
# Set PIXIE_HOST_ADDR to the LAN address this box answers on.
# Set PIXIE_ADMIN_PASSWORD to something other than the default.
"${{EDITOR:-vi}}" envvars

COMPOSE_ENV_FILES=envvars podman compose up -d
```

The container's HTTP server binds ``127.0.0.1:{http_port}`` and, when
targets bind nbdboot, spawns one nbdkit per export starting at TCP
``{nbd_port}``. ``pixie-lab deploy`` runs the compose bring-up for
you, filling in envvars if it's empty.

## Tear down

```
podman compose --env-file envvars down -v
```

Or ``pixie-lab purge`` from this directory.

## Docs

See ``PLAN.md`` at github.com/safl/pixie for the design rationale
and roadmap.
"""


def compose_yaml(*, image: str, admin_password: str) -> str:
    return COMPOSE_YAML.format(image=image, admin_password=admin_password)


def envvars_example(*, admin_password: str) -> str:
    return ENVVARS_EXAMPLE.format(admin_password=admin_password)


def readme_md(*, http_port: int = DEFAULT_HTTP_PORT, nbd_port: int = DEFAULT_NBD_PORT_BASE) -> str:
    return README_MD.format(http_port=http_port, nbd_port=nbd_port)


def emitted_files(dest: str, image: str) -> dict[str, Any]:
    """The three files a fresh ``pixie-lab init`` writes, plus the
    ``data/`` scaffold. Returned as a dict so tests can assert
    specific bytes without touching the filesystem."""
    return {
        f"{dest}/compose.yml": compose_yaml(image=image, admin_password=DEFAULT_ADMIN_PASSWORD),
        f"{dest}/envvars.example": envvars_example(admin_password=DEFAULT_ADMIN_PASSWORD),
        f"{dest}/README.md": readme_md(),
    }
